name: Cleanup Artifacts

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * 0'  # 每周日运行一次
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        retention-days: 1  # 保留最近30天的工件
