name: Build and Push with Nuitka

on:
  workflow_dispatch: # 手动触发

jobs:
  build-arm64:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip patchelf
        python3 -m pip install --upgrade pip
        pip install nuitka

    - name: Compile with Nuitka
      run: |
        python3 -m nuitka --standalone --onefile --remove-output app.py

    - name: List files
      run: ls -R .

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add app.bin
        git commit -m "Add compiled app.bin"
        git push origin master