name: Build Static Node.js

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3

    - name: Build static Node.js
      run: |
        git clone --depth=1 --branch=v18.20.8 https://github.com/nodejs/node.git
        cd node
        ./configure --fully-static --enable-static --without-npm --without-corepack
        make -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: static-node
        path: node/out/Release/node
